firstproject/Controllers/AddpgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using firstproject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace firstproject.Controllers
{
    public class AddpgController : Controller
    {

        private readonly IWebHostEnvironment _webHostEnvironment;
        public AddpgController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }


        public async Task<string> UploadImage(string folderpath, IFormFile file)
        {
            folderpath += Guid.NewGuid().ToString() + "_" + file.FileName;
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderpath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderpath;
        }


        DataContext dal = new DataContext();
        public IActionResult Add()
        {

            //selec all record
            var dataselect = dal.pgs.ToList();
            ViewBag.data = dataselect;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Insert(Addpg pg, IFormFile file)
        {
            string folder = "image/pgimage/";

            Addpg obj = new Addpg()
            {
                id = pg.id,
                title=pg.title,
                type=pg.type,
                district=pg.district,
                city=pg.city,
                rent=pg.rent,
                rooms=pg.rooms,
                email=pg.email,
                address=pg.address,
                picture= await UploadImage(folder,file),
                electricity =pg.electricity,
                ac=pg.ac,
                fan=pg.fan,
                parking=pg.parking,
                furnished=pg.furnished,
                internet=pg.internet,
                security=pg.security,
                types=pg.types
            };

            dal.pgs.Add(obj);
            dal.SaveChanges();
            return RedirectToAction("Add");

        }

        public string OpenPopup()
        {
            return " Data added successfully!";
        }

    }
}

firstproject/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using firstproject.Models;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Http;

namespace firstproject.Controllers
{
    public class LoginController : Controller
    {
        DataContext dal = new DataContext();
        public IActionResult log()
         {
             //if (HttpContext.Session.GetString("id")!=null)
             //{
             //return View();
             //}
             // else
             //{
            //select all records
            List<Login> data = dal.login.ToList();
            ViewBag.data = data;
          return View();
         //}
         }

        [HttpPost]
        public IActionResult LoginCheck(Login logn)
        {
            //insert
            dal.login.Add(logn);
            dal.SaveChanges();
            ViewData["Message"] = "Login is succesfull";
            return RedirectToAction("astu","Astina");
        }
        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public ActionResult Login(string email, string password)
        //    {
        //        if (ModelState.IsValid)
        //        {


        //            var f_password = GetMD5(password);
        //            var data = dal.Logins.Where(s => s.Email.Equals(email) && s.Password.Equals(f_password)).ToList();
        //            if (data.Count() > 0)
        //            {
        //                add session
        //                 Session["Password"] = data.FirstOrDefault().Password;
        //                 Session["Email"] = data.FirstOrDefault().Email;
        //                 Session["id"] = data.FirstOrDefault().id;
        //                return RedirectToAction("Index");
        //            }
        //            else
        //            {
        //                ViewBag.error = "Login failed";
        //                return RedirectToAction("Login");
        //            }
        //        }
        //        return View();
        //    }
        //    public static string GetMD5(string str)
        //    {
        //        MD5 md5 = new MD5CryptoServiceProvider();
        //        byte[] fromData = Encoding.UTF8.GetBytes(str);
        //        byte[] targetData = md5.ComputeHash(fromData);
        //        string byte2String = null;

        //        for (int i = 0; i < targetData.Length; i++)
        //        {
        //            byte2String += targetData[i].ToString("x2");

        //        }
        //        return byte2String;
        //    }
        //}
    }
}

firstproject/Controllers/OwnconController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace firstproject.Controllers
{
    public class OwnconController : Controller
    {
        public IActionResult dex()
        {
            return View();
        }
    }
}

firstproject/Controllers/SigninController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using firstproject.Models;
namespace firstproject.Controllers
{

    public class SigninController : Controller
    {
        DataContext dal = new DataContext();

        public ActionResult Sign()
        {
            return View("sign");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Sign(Signin register)
        {

            if (ModelState.IsValid)
            {
                using (var dal = new DataContext())
                {

                    Signin ss = new Signin();
                    ss.Email = register.Email;
                    ss.Name = register.Name;
                    ss.Password = register.Password;
                    dal.Signins.Add(ss);
                    dal.SaveChanges();
                }

                ViewData["Message"] = "User Details Saved";
                return View("sign");
            }
            else
            {

                return View("sign", register);
            }
        }
    }
            }
 

firstproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-image: url('/image/back1.jpg');
            background-attachment: fixed;
            background-size: cover;
        }
        
    </style>
</head>

 
<body data-spy="scroll" data-target=".navbar" data-offset="50">
    <header>
        <nav class="navbar navbar-expand-sm bg-info navbar-light" style="height:-100px;">
            <div class="container">
                <img src="~/image/logo.png" class="rounded" alt="Cinque Terre" height="50px" width="fit-content">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Contact" asp-action="contactus">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Login" asp-action="log">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Signin" asp-action="Sign">Sign In</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

firstproject/Views/Shared/_layoutAdmin.cshtml
@{
    Layout = null;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<html>
<body>
    <div class="back">
        <style>
            body {
                background-image: url('/image/home1.jpeg');
                background-attachment: fixed;
                background-size: cover;
            }
            .dropdown-menu{
                background-color:deepskyblue;
            }
            .back a:hover {
                background-color: greenyellow;
                color: black;
            }
        </style>
        <nav class="navbar navbar-expand-sm bg-info navbar-light">
            <!-- Brand -->
            <a class="navbar-brand" href="#" style="margin-left:30px"><img src="~/image/logo.png" width="fit-content" height="50px" class="rounded" alt="Cinque Terre" /></a>

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-dark font-weight-bold" href="#" style="margin-left:30px">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark font-weight-bold" id="navbardrop" data-toggle="dropdown" asp-controller="Addpg" asp-action="Add" style="margin-left:30px">State</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="" asp-action="">Add</a>
                        <a class="dropdown-item" asp-controller="" asp-action="">Update</a>
                        <a class="dropdown-item" asp-controller="" asp-action="">Delete</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark font-weight-bold" asp-controller="" asp-action="" style="margin-left:30px">City</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="" asp-action="">Add</a>
                        <a class="dropdown-item" asp-controller="" asp-action="">Update</a>
                        <a class="dropdown-item" asp-controller="" asp-action="">Delete</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark font-weight-bold" asp-controller="" asp-action="" style="margin-left:30px">Reg Owner</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="" asp-action="">View</a>
                        <a class="dropdown-item" asp-controller="" asp-action="">Edit</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark font-weight-bold" asp-controller="" asp-action="" style="margin-left:30px">PG Details</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark font-weight-bold" style="margin-left:30px" asp-controller="" asp-action="">Pages</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="" asp-action="">About Us</a>
                        <a class="dropdown-item" asp-controller="" asp-action="">Contact Us</a>
                    </div>
                </li>


                <li class="nav-item">
                    <a class="nav-link text-dark font-weight-bold" href="#" style="margin-left:30px">Log Out</a>
                </li>

            </ul>
        </nav>
    </div>
    <div>
        @RenderBody();
    </div>
</body>
</html>

firstproject/Views/Shared/_layoutOwner.cshtml
@{
    Layout = null;
}

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/lib/jquery-datatables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/lib/jquery-datatables/js/jquery.dataTables.min.js"></script>
    <!-- The sidebar -->
    <style>
        body {
            background-image: url('/image/owns2.jpg');
            background-attachment: fixed;
            background-size: cover;
        }

        .sidebar {
            margin: 0;
            padding: 0;
            width: 220px;
            background-color: deepskyblue;
            position: fixed;
            height: 100%;
            overflow: auto;
        }
            /* Style sidebar links */
            .sidebar a {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                font-size: 20px;
                color: black;
                display: block;
            }

                .sidebar a.active {
                    background-color: greenyellow;
                    color: black;
                }
                /* Style links on mouse-over */
                .sidebar a:hover {
                    background-color: greenyellow;
                    color: black;
                }

        /* Style the main content */
        .main {
            margin-left: 160px; /* Same as the width of the sidenav */
            padding: 0px 10px;
        }
    </style>
</head>

<body>

    <div class="sidebar">
        <center><img src="~/image/logo.png" class="rounded" alt="Cinque Terre" height="50px" width="fit-content"></center><br />
        <a href="#home" class="active"><i class="fa fa-fw fa-home"></i> Home</a>
        <a asp-controller="Addpg" asp-action="Add" style="text-decoration:none;margin-top:10px;"><i class="fa fa-fw fa-plus"></i> Add PG</a>
        <a asp-controller="Updatepg" asp-action="Update" style="text-decoration:none;margin-top:10px;"><i class="fa fa-fw fa-eye"></i> View PG</a>
        <a style="text-decoration: none; margin-top: 10px;"><i class="fa fa-fw fa-envelope"></i>Message</a>
        <a asp-controller="Owncon" asp-action="dex" style="text-decoration:none;margin-top:10px;"><i class="fa fa-fw fa-phone"></i> Contact Us</a>
        <a style="text-decoration:none;margin-right:10px;"><i class="fa fa-fw fa-user"></i>About Us</a>
        <a style="text-decoration:none;margin-top:10px;"><i class="fa fa-fw fa-exchange"></i>Change Password</a>
        <a style="text-decoration:none;margin-top:10px;" asp-controller="Logoutpg" asp-action="logout"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
    </div>
    <div>
        @RenderBody();
    </div>
</body>
</html>
@RenderSection("Scripts", required: false)